using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GroupAndJoinData
{
    class Database
    {
        public IEnumerable<Country> Countries
        {
            get { return countries; }
        }

        public IEnumerable<City> Cities
        {
            get { return cities; }
        }

        #region Countries
        static Country[] countries = new Country[]
        {
            new Country { Name = "China", Population = 1339724852 },
            new Country { Name = "India", Population = 1210193422 },
            new Country { Name = "United States", Population = 312771000 },
            new Country { Name = "Indonesia", Population = 237641326 },
            new Country { Name = "Brazil", Population = 190755799 },
            new Country { Name = "Pakistan", Population = 178079000 },
            new Country { Name = "Nigeria", Population = 162471000 },
            new Country { Name = "Russia", Population = 142914136 },
            new Country { Name = "Bangladesh", Population = 142319000 },
            new Country { Name = "Japan", Population = 127720000 },
            new Country { Name = "Mexico", Population = 112336538 },
            new Country { Name = "Philippines", Population = 94013200 },
            new Country { Name = "Vietnam", Population = 85846997 },
            new Country { Name = "Ethiopia", Population = 82101998 },
            new Country { Name = "Germany", Population = 81729000 },
            new Country { Name = "Egypt", Population = 81238000 },
            new Country { Name = "Iran", Population = 75912000 },
            new Country { Name = "Turkey", Population = 73722988 },
            new Country { Name = "Thailand", Population = 69519000 },
            new Country { Name = "Democratic Republic of the Congo", Population = 67758000 },
            new Country { Name = "France", Population = 65027000 },
            new Country { Name = "United Kingdom", Population = 62300000 },
            new Country { Name = "Italy", Population = 60705991 },
            new Country { Name = "South Africa", Population = 50586757 },
            new Country { Name = "Myanmar", Population = 48337000 },
            new Country { Name = "South Korea", Population = 48219000 },
            new Country { Name = "Colombia", Population = 46291000 },
            new Country { Name = "Spain", Population = 46162024 },
            new Country { Name = "Ukraine", Population = 45668028 },
            new Country { Name = "Tanzania", Population = 43188000 },
            new Country { Name = "Argentina", Population = 40117096 },
            new Country { Name = "Kenya", Population = 38610097 },
            new Country { Name = "Poland", Population = 38092000 },
            new Country { Name = "Algeria", Population = 36300000 },
            new Country { Name = "Canada", Population = 34482779 },
            new Country { Name = "Uganda", Population = 32939800 },
            new Country { Name = "Morocco", Population = 32404700 },
            new Country { Name = "Afghanistan", Population = 32358000 },
            new Country { Name = "Iraq", Population = 32105000 },
            new Country { Name = "Sudan", Population = 30894000 },
            new Country { Name = "Peru", Population = 29797694 },
            new Country { Name = "Venezuela", Population = 29478000 },
            new Country { Name = "Malaysia", Population = 28334135 },
            new Country { Name = "Uzbekistan", Population = 28000000 },
            new Country { Name = "Saudi Arabia", Population = 27136977 },
            new Country { Name = "Nepal", Population = 26620809 },
            new Country { Name = "Ghana", Population = 24233431 },
            new Country { Name = "North Korea", Population = 24052231 },
            new Country { Name = "Yemen", Population = 23833000 },
            new Country { Name = "Taiwan", Population = 23197947 },
            new Country { Name = "Mozambique", Population = 23049621 },
            new Country { Name = "Australia", Population = 22790368 },
            new Country { Name = "Romania", Population = 21436000 },
            new Country { Name = "Côte d'Ivoire", Population = 21395000 },
            new Country { Name = "Syria", Population = 21352000 },
            new Country { Name = "Sri Lanka", Population = 20653000 },
            new Country { Name = "Angola", Population = 19618000 },
            new Country { Name = "Cameroon", Population = 19406100 },
            new Country { Name = "Madagascar", Population = 18866000 },
            new Country { Name = "Chile", Population = 17248450 },
            new Country { Name = "Netherlands", Population = 16715489 },
            new Country { Name = "Kazakhstan", Population = 16615000 },
            new Country { Name = "Burkina Faso", Population = 15730977 },
            new Country { Name = "Niger", Population = 15730754 },
            new Country { Name = "Guatemala", Population = 14713763 },
            new Country { Name = "Mali", Population = 14517176 },
            new Country { Name = "Ecuador", Population = 14483499 },
            new Country { Name = "Cambodia", Population = 13395682 },
            new Country { Name = "Malawi", Population = 13077160 },
            new Country { Name = "Zambia", Population = 13046508 },
            new Country { Name = "Senegal", Population = 12855153 },
            new Country { Name = "Zimbabwe", Population = 12754000 },
            new Country { Name = "Chad", Population = 11274106 },
            new Country { Name = "Cuba", Population = 11241161 },
            new Country { Name = "Belgium", Population = 10839905 },
            new Country { Name = "Greece", Population = 10787690 },
            new Country { Name = "Rwanda", Population = 10718379 },
            new Country { Name = "Tunisia", Population = 10673800 },
            new Country { Name = "Portugal", Population = 10561614 },
            new Country { Name = "Czech Republic", Population = 10542080 },
            new Country { Name = "Bolivia", Population = 10426154 },
            new Country { Name = "Guinea", Population = 10217591 },
            new Country { Name = "Haiti", Population = 10085214 },
            new Country { Name = "Hungary", Population = 9985722 },
            new Country { Name = "Somalia", Population = 9557000 },
            new Country { Name = "Sweden", Population = 9475954 },
            new Country { Name = "Belarus", Population = 9466700 },
            new Country { Name = "Dominican Republic", Population = 9378818 },
            new Country { Name = "Azerbaijan", Population = 9111100 },
            new Country { Name = "Benin", Population = 9100000 },
            new Country { Name = "Burundi", Population = 8575000 },
            new Country { Name = "Austria", Population = 8419776 },
            new Country { Name = "United Arab Emirates", Population = 8264070 },
            new Country { Name = "South Sudan", Population = 8260490 },
            new Country { Name = "Honduras", Population = 8215313 },
            new Country { Name = "Switzerland", Population = 7870100 },
            new Country { Name = "Israel", Population = 7811900 },
            new Country { Name = "Tajikistan", Population = 7616000 },
            new Country { Name = "Bulgaria", Population = 7364570 },
            new Country { Name = "Serbia", Population = 7120666 },
            new Country { Name = "Hong Kong", Population = 7108100 },
            new Country { Name = "Papua New Guinea", Population = 7014000 },
            new Country { Name = "Libya", Population = 6423000 },
            new Country { Name = "Laos", Population = 6348800 },
            new Country { Name = "Paraguay", Population = 6337127 },
            new Country { Name = "Jordan", Population = 6242500 },
            new Country { Name = "El Salvador", Population = 6227000 },
            new Country { Name = "Sierra Leone", Population = 5997000 },
            new Country { Name = "Nicaragua", Population = 5815524 },
            new Country { Name = "Togo", Population = 5753324 },
            new Country { Name = "Denmark", Population = 5579204 },
            new Country { Name = "Kyrgyzstan", Population = 5477600 },
            new Country { Name = "Slovakia", Population = 5437126 },
            new Country { Name = "Eritrea", Population = 5415000 },
            new Country { Name = "Finland", Population = 5401376 },
            new Country { Name = "Singapore", Population = 5183700 },
            new Country { Name = "Turkmenistan", Population = 5105000 },
            new Country { Name = "Norway", Population = 4989700 },
            new Country { Name = "Ireland", Population = 4581269 },
            new Country { Name = "Costa Rica", Population = 4563539 },
            new Country { Name = "Central African Republic", Population = 4487000 },
            new Country { Name = "Georgia", Population = 4469200 },
            new Country { Name = "New Zealand", Population = 4431700 },
            new Country { Name = "Croatia", Population = 4290612 },
            new Country { Name = "Lebanon", Population = 4259000 },
            new Country { Name = "Palestinian territories", Population = 4168858 },
            new Country { Name = "Republic of the Congo", Population = 4140000 },
            new Country { Name = "Bosnia and Herzegovina", Population = 3843126 },
            new Country { Name = "Puerto Rico", Population = 3725789 },
            new Country { Name = "Moldova", Population = 3560400 },
            new Country { Name = "Liberia", Population = 3476608 },
            new Country { Name = "Panama", Population = 3405813 },
            new Country { Name = "Uruguay", Population = 3368595 },
            new Country { Name = "Mauritania", Population = 3340627 },
            new Country { Name = "Armenia", Population = 3266300 },
            new Country { Name = "Lithuania", Population = 3207100 },
            new Country { Name = "Albania", Population = 3194972 },
            new Country { Name = "Kuwait", Population = 2818000 },
            new Country { Name = "Oman", Population = 2773479 },
            new Country { Name = "Mongolia", Population = 2736800 },
            new Country { Name = "Jamaica", Population = 2705800 },
            new Country { Name = "Namibia", Population = 2324000 },
            new Country { Name = "Latvia", Population = 2209000 },
            new Country { Name = "Lesotho", Population = 2194000 },
            new Country { Name = "Macedonia", Population = 2057284 },
            new Country { Name = "Slovenia", Population = 2055480 },
            new Country { Name = "Botswana", Population = 2031000 },
            new Country { Name = "Gambia", Population = 1776000 },
            new Country { Name = "Qatar", Population = 1699435 },
            new Country { Name = "Gabon", Population = 1534000 },
            new Country { Name = "Guinea-Bissau", Population = 1520830 },
            new Country { Name = "Estonia", Population = 1340194 },
            new Country { Name = "Trinidad and Tobago", Population = 1317714 },
            new Country { Name = "Mauritius", Population = 1280924 },
            new Country { Name = "Bahrain", Population = 1234571 },
            new Country { Name = "Swaziland", Population = 1203000 },
            new Country { Name = "Timor-Leste", Population = 1066409 },
            new Country { Name = "Fiji", Population = 868000 },
            new Country { Name = "Djibouti", Population = 818159 },
            new Country { Name = "Réunion", Population = 808250 },
            new Country { Name = "Cyprus", Population = 803200 },
            new Country { Name = "Guyana", Population = 784894 },
            new Country { Name = "Comoros", Population = 754000 },
            new Country { Name = "Equatorial Guinea", Population = 720000 },
            new Country { Name = "Bhutan", Population = 708265 },
            new Country { Name = "Montenegro", Population = 620029 },
            new Country { Name = "Macau ", Population = 560100 },
            new Country { Name = "Western Sahara", Population = 548000 },
            new Country { Name = "Solomon Islands", Population = 542287 },
            new Country { Name = "Suriname", Population = 529000 },
            new Country { Name = "Luxembourg", Population = 511840 },
            new Country { Name = "Cape Verde", Population = 491575 },
            new Country { Name = "Brunei", Population = 422700 },
            new Country { Name = "Malta", Population = 417617 },
            new Country { Name = "Guadeloupe", Population = 401784 },
            new Country { Name = "Martinique", Population = 397693 },
            new Country { Name = "Bahamas", Population = 353658 },
            new Country { Name = "Iceland", Population = 318452 },
            new Country { Name = "Maldives", Population = 317280 },
            new Country { Name = "Belize", Population = 312698 },
            new Country { Name = "Barbados", Population = 276302 },
            new Country { Name = "French Polynesia", Population = 274000 },
            new Country { Name = "New Caledonia", Population = 245580 },
            new Country { Name = "Vanuatu", Population = 234023 },
            new Country { Name = "French Guiana", Population = 219266 },
            new Country { Name = "Mayotte", Population = 211000 },
            new Country { Name = "Samoa", Population = 184032 },
            new Country { Name = "São Tomé and Príncipe", Population = 169000 },
            new Country { Name = "Saint Lucia", Population = 166526 },
            new Country { Name = "Guam", Population = 159358 },
            new Country { Name = "Curaçao ", Population = 142180 },
            new Country { Name = "Grenada", Population = 110821 },
            new Country { Name = "United States Virgin Islands", Population = 106405 },
            new Country { Name = "Tonga", Population = 105000 },
            new Country { Name = "Federated States of Micronesia", Population = 102624 },
            new Country { Name = "Aruba ", Population = 101484 },
            new Country { Name = "Kiribati", Population = 101000 },
            new Country { Name = "Saint Vincent and the Grenadines", Population = 100892 },
            new Country { Name = "Jersey ", Population = 92500 },
            new Country { Name = "Seychelles", Population = 90945 },
            new Country { Name = "Antigua and Barbuda", Population = 89138 },
            new Country { Name = "Andorra", Population = 85015 },
            new Country { Name = "Isle of Man ", Population = 83000 },
            new Country { Name = "Dominica", Population = 71685 },
            new Country { Name = "Bermuda ", Population = 64186 },
            new Country { Name = "Guernsey ", Population = 62431 },
            new Country { Name = "Greenland ", Population = 56890 },
            new Country { Name = "American Samoa", Population = 55519 },
            new Country { Name = "Cayman Islands ", Population = 54878 },
            new Country { Name = "Marshall Islands", Population = 54305 },
            new Country { Name = "Northern Mariana Islands ", Population = 53883 },
            new Country { Name = "Saint Kitts and Nevis", Population = 51970 },
            new Country { Name = "Faroe Islands ", Population = 48738 },
            new Country { Name = "Turks and Caicos Islands ", Population = 42375 },
            new Country { Name = "Saint Martin ", Population = 37163 },
            new Country { Name = "Liechtenstein", Population = 36157 },
            new Country { Name = "Monaco", Population = 35881 },
            new Country { Name = "San Marino", Population = 32093 },
            new Country { Name = "Gibraltar ", Population = 29441 },
            new Country { Name = "British Virgin Islands ", Population = 28213 },
            new Country { Name = "Palau", Population = 21000 },
            new Country { Name = "Anguilla ", Population = 15236 },
            new Country { Name = "Wallis and Futuna ", Population = 13445 },
            new Country { Name = "Cook Islands ", Population = 10900 },
            new Country { Name = "Nauru", Population = 10000 },
            new Country { Name = "Tuvalu", Population = 10000 },
            new Country { Name = "Saint Barthélemy ", Population = 8823 },
            new Country { Name = "Saint Pierre and Miquelon ", Population = 6290 },
            new Country { Name = "Montserrat ", Population = 4932 },
            new Country { Name = "Saint Helena, Ascension and Tristan da Cunha ", Population = 4255 },
            new Country { Name = "Falkland Islands ", Population = 3000 },
            new Country { Name = "Niue ", Population = 1000 },
            new Country { Name = "Tokelau ", Population = 1000 },
            new Country { Name = "Vatican City", Population = 800 },
        
        };
        #endregion

        #region Cities
        static City[] cities = new City[]
        {
            new City { CityName = "Tokyo", CountryName = "Japan", CityPopulation = 32450000 },
            new City { CityName = "Seóul", CountryName = "South Korea", CityPopulation = 20550000 },
            new City { CityName = "Mexico City", CountryName = "Mexico", CityPopulation = 20450000 },
            new City { CityName = "New York City", CountryName = "United States", CityPopulation = 19750000 },
            new City { CityName = "Mumbai", CountryName = "India", CityPopulation = 19200000 },
            new City { CityName = "Jakarta", CountryName = "Indonesia", CityPopulation = 18900000 },
            new City { CityName = "Sáo Paulo", CountryName = "Brazil", CityPopulation = 18850000 },
            new City { CityName = "Delhi", CountryName = "India", CityPopulation = 18680000 },
            new City { CityName = "Õsaka/Kobe", CountryName = "Japan", CityPopulation = 17350000 },
            new City { CityName = "Shanghai", CountryName = "China", CityPopulation = 16650000 },
            new City { CityName = "Manila", CountryName = "Philippines", CityPopulation = 16300000 },
            new City { CityName = "Los Angeles", CountryName = "United States", CityPopulation = 15250000 },
            new City { CityName = "Calcutta", CountryName = "India", CityPopulation = 15100000 },
            new City { CityName = "Moscow", CountryName = "Russia", CityPopulation = 15000000 },
            new City { CityName = "Cairo", CountryName = "Egypt", CityPopulation = 14450000 },
            new City { CityName = "Lagos", CountryName = "Nigeria", CityPopulation = 13488000 },
            new City { CityName = "Buenos Aires", CountryName = "Argentina", CityPopulation = 13170000 },
            new City { CityName = "London", CountryName = "United Kingdom", CityPopulation = 12875000 },
            new City { CityName = "Beijing", CountryName = "China", CityPopulation = 12500000 },
            new City { CityName = "Karachi", CountryName = "Pakistan", CityPopulation = 11800000 },
            new City { CityName = "Dhaka", CountryName = "Bangladesh", CityPopulation = 10979000 },
            new City { CityName = "Rio de Janeiro", CountryName = "Brazil", CityPopulation = 10556000 },
            new City { CityName = "Tianjin", CountryName = "China", CityPopulation = 10239000 },
            new City { CityName = "Paris", CountryName = "France", CityPopulation = 9638000 },
            new City { CityName = "Istanbul", CountryName = "Turkey", CityPopulation = 9413000 },
            new City { CityName = "Lima", CountryName = "Peru", CityPopulation = 7443000 },
            new City { CityName = "Tehrãn", CountryName = "Iran", CityPopulation = 7380000 },
            new City { CityName = "Bangkok", CountryName = "Thailand", CityPopulation = 7221000 },
            new City { CityName = "Chicago", CountryName = "United States", CityPopulation = 6945000 },
            new City { CityName = "Bogotá", CountryName = "Colombia", CityPopulation = 6834000 },
            new City { CityName = "Hyderabad", CountryName = "India", CityPopulation = 6833000 },
            new City { CityName = "Chennai", CountryName = "India", CityPopulation = 6639000 },
            new City { CityName = "Essen", CountryName = "Germany", CityPopulation = 6559000 },
            new City { CityName = "Ho Chi Minh City", CountryName = "Vietnam", CityPopulation = 6424519 },
            new City { CityName = "Hangzhou", CountryName = "China", CityPopulation = 6389000 },
            new City { CityName = "Hong Kong", CountryName = "China", CityPopulation = 6097000 },
            new City { CityName = "Lahore", CountryName = "Pakistan", CityPopulation = 6030000 },
            new City { CityName = "Shenyang", CountryName = "China", CityPopulation = 5681000 },
            new City { CityName = "Changchun", CountryName = "China", CityPopulation = 5566000 },
            new City { CityName = "Bangalore", CountryName = "India", CityPopulation = 5544000 },
            new City { CityName = "Harbin", CountryName = "China", CityPopulation = 5475000 },
            new City { CityName = "Chengdu", CountryName = "China", CityPopulation = 5293000 },
            new City { CityName = "Santiago", CountryName = "Chile", CityPopulation = 5261000 },
            new City { CityName = "Guangzhou", CountryName = "China", CityPopulation = 5162000 },
            new City { CityName = "Kinshasa", CountryName = "DRC", CityPopulation = 5068000 },
            new City { CityName = "Baghdãd", CountryName = "Iraq", CityPopulation = 4796000 },
            new City { CityName = "Jinan", CountryName = "China", CityPopulation = 4789000 },
            new City { CityName = "Houston", CountryName = "United States", CityPopulation = 4750000 },
            new City { CityName = "Toronto", CountryName = "Canada", CityPopulation = 4657000 },
            new City { CityName = "Yangon", CountryName = "Myanmar", CityPopulation = 4458000 },
            new City { CityName = "Alger", CountryName = "Algeria", CityPopulation = 4447000 },
            new City { CityName = "Philadelphia", CountryName = "United States", CityPopulation = 4398000 },
            new City { CityName = "Qingdao", CountryName = "China", CityPopulation = 4376000 },
            new City { CityName = "Milano", CountryName = "Italy", CityPopulation = 4251000 },
            new City { CityName = "PUnited Statesn", CountryName = "South Korea", CityPopulation = 4239000 },
            new City { CityName = "Belo Horizonte", CountryName = "Brazil", CityPopulation = 4160000 },
            new City { CityName = "Almadabad", CountryName = "India", CityPopulation = 4154000 },
            new City { CityName = "Madrid", CountryName = "Spain", CityPopulation = 4072000 },
            new City { CityName = "San Francisco", CountryName = "United States", CityPopulation = 4051000 },
            new City { CityName = "Alexandria", CountryName = "Egypt", CityPopulation = 3995000 },
            new City { CityName = "Washington DC", CountryName = "United States", CityPopulation = 3927000 },
            new City { CityName = "Wuhan", CountryName = "China", CityPopulation = 3918000 },
            new City { CityName = "Dallas", CountryName = "United States", CityPopulation = 3912000 },
            new City { CityName = "Guadalajara", CountryName = "Mexico", CityPopulation = 3908000 },
            new City { CityName = "Chongging", CountryName = "China", CityPopulation = 3896000 },
            new City { CityName = "Medellin", CountryName = "Colombia", CityPopulation = 3831000 },
            new City { CityName = "Detroit", CountryName = "United States", CityPopulation = 3785000 },
            new City { CityName = "Handan", CountryName = "China", CityPopulation = 3763000 },
            new City { CityName = "Frankfurt", CountryName = "Germany", CityPopulation = 3700000 },
            new City { CityName = "Porto Alegre", CountryName = "Brazil", CityPopulation = 3699000 },
            new City { CityName = "Hanoi", CountryName = "Vietnam", CityPopulation = 3678000 },
            new City { CityName = "Sydney", CountryName = "Australia", CityPopulation = 3665000 },
            new City { CityName = "Singapore", CountryName = "Singapore", CityPopulation = 3587000 },
            new City { CityName = "Casablanca", CountryName = "Morocco", CityPopulation = 3535000 },
            new City { CityName = "Katowice", CountryName = "Poland", CityPopulation = 3488000 },
            new City { CityName = "Pune", CountryName = "India", CityPopulation = 3485000 },
            new City { CityName = "Bangdung", CountryName = "Indonesia", CityPopulation = 3420000 },
            new City { CityName = "Monterrey", CountryName = "Mexico", CityPopulation = 3416000 },
            new City { CityName = "Montréal", CountryName = "Canada", CityPopulation = 3401000 },
            new City { CityName = "Nagoya", CountryName = "Japan", CityPopulation = 3377000 },
            new City { CityName = "Nanjing", CountryName = "China", CityPopulation = 3375000 },
            new City { CityName = "Abidjan", CountryName = "Côte d'Ivoire", CityPopulation = 3359000 },
            new City { CityName = "Xi'an", CountryName = "China", CityPopulation = 3352000 },
            new City { CityName = "Berlin", CountryName = "Germany", CityPopulation = 3337000 },
            new City { CityName = "Riyadh", CountryName = "Saudi Arabia", CityPopulation = 3328000 },
            new City { CityName = "Recife", CountryName = "Brazil", CityPopulation = 3307000 },
            new City { CityName = "Dusseldorf", CountryName = "Germany", CityPopulation = 3251000 },
            new City { CityName = "Ankara", CountryName = "Turkey", CityPopulation = 3190000 },
            new City { CityName = "Melbourne", CountryName = "Australia", CityPopulation = 3188000 },
            new City { CityName = "Salvador", CountryName = "Brazil", CityPopulation = 3180000 },
            new City { CityName = "Dalian", CountryName = "China", CityPopulation = 3153000 },
            new City { CityName = "Caracas", CountryName = "Venezuela", CityPopulation = 3153000 },
            new City { CityName = "Adis Abeba", CountryName = "Ethiopia", CityPopulation = 3112000 },
            new City { CityName = "Athina", CountryName = "Greece", CityPopulation = 3103000 },
            new City { CityName = "Cape Town", CountryName = "South Africa", CityPopulation = 3092000 },
            new City { CityName = "Maputo", CountryName = "Mozambique", CityPopulation = 3017000 },
            new City { CityName = "Napoli", CountryName = "Italy", CityPopulation = 3012000 },
        };
        #endregion
    }

    class Country
    {
        public string Name { get; set; }
        public int Population { get; set; }
    }

    class City
    {
        public string CityName { get; set; }
        public int CityPopulation { get; set; }
        public string CountryName { get; set; }
    }
}
